services:
  - type: web
    name: polyclinic-website
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
